# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{purple_ruby}
  s.version = "0.6.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["yong"]
  s.date = %q{2010-05-13}
  s.description = %q{A ruby gem to write server that sends and receives IM messages}
  s.email = %q{yong@intridea.com}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/purplegw_example.rb",
     "ext/account.c",
     "ext/extconf.rb",
     "ext/purple_ruby_ext.c",
     "ext/reconnect.c",
     "lib/purple_ruby.rb",
     "purple_ruby.gemspec",
     "spec/purple_ruby_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/purple_ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Gem to send and receive IM messages}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/purple_ruby_spec.rb",
     "examples/purplegw_example.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

